### ISSUE TITLE
Error when using "tab" argument in constructor

### ISSUE THREAD

**Issue by sdondley** [Corion/WWW-Mechanize-Chrome#19]
`tab =>` argument appears to be buggy. Tried setting it to `current`, `0`, and `qr/about/` and WMC crashes with:

`error when connectingInternal Exception at /Users/me/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.4/WWW/Mechanize/Chrome.pm line 533`

**Comment by Corion** [comment]
Is this still a problem? t/50-mech-new.t tests for these cases and the tests pass in recent versions.

If you can add a short program that still fails, this would be great, otherwise I'll close the issue in a week or so.

Thanks!
