### ISSUE TITLE
Warning: Use of uninitialized value

### ISSUE THREAD

**Issue by KES777** [Corion/WWW-Mechanize-Chrome#27]
Sometimes I get this warnings:

```
Use of uninitialized value $event in hash element at /home/kes/work/projects/tucha//local/lib/perl5/Chrome/DevToolsProtocol.pm line 235 during global destruction.
```

lines are: 234, 235, 237

**Comment by Corion** [comment]
Sorry for responding only now. This is most likely related to objects going away too early during global destruction but I'll make the code more resilient against that!

Thanks for notifying me about that!

**Comment by KES777** [comment]
>Sorry for responding **only now**

Thank you for fixes
