### ISSUE TITLE
Add example how to setup pagesize

### ISSUE THREAD

**Issue by KES777** [Corion/WWW-Mechanize-Chrome#28]
When I save pages as pdf they are saved us `US Letter`

[here](https://developers.google.com/web/updates/2017/04/headless-chrome#node) I can see an examples that chrome allow parameter to set page size:

    await page.pdf({path: 'page.pdf', format: 'A4'});

I did not find how to setup this with help of your module. If this is possible may you please create an example?

I try to workaround that with `@page{ size: A4 }` but there is [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=724160) in Chrome

**Comment by KES777** [comment]
info: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF

**Comment by Corion** [comment]
Heh - `->content_as_pdf` and `->render_content` pass their options through, so the following should already work even though it is undocumented:

    my $pdf = $mech->content_as_pdf( format => 'A4' );

I'll add that to the documentation, thanks for reporting this!

**Comment by Corion** [comment]
Released as 0.20, thanks!
