### ISSUE TITLE
Failed test when installing

### ISSUE THREAD

**Issue by sdondley** [Corion/WWW-Mechanize-Chrome#33]
Trying to install on a Mac with Chrome  v. 70.0.3538.110.

I'm failing a test:

```
#   Failed test 'The two links were found'
#   at t/51-mech-links.t line 72.
#          got: '3'
#     expected: '2'
# relative
# myiframe
# http://searchguide.level3.com/search/?q=http://somewhere.example/myiframe&t=0
# Looks like you failed 1 test of 7.
t/51-mech-links.t ................
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests
```

**Comment by Corion** [comment]
Hello Steve,

this seems to be an indication that your machine or your browser has been infected by some "Search Plugin" redirector. The complete distribution doesn't contain the words `searchguide.level3.com` or `searchguide`. Either you have installed a nasty browser plugin that secretly shares "your" surf data with the outside world or your machine itself has been infected by such a program. At least a cursory Google search for `searchguide.level3.com` turns up lots of pages that claim to help removing something like this, but I don't know which site or what recipe is a good recipe there.

Sorry to be the bearer of bad news...

**Comment by sdondley** [comment]
Thanks for getting back. Turned out it was an extension that helped me find content in open tabs. I turned it off and I get no more error on installation now.
