### ISSUE TITLE
Docs missing?

### ISSUE THREAD

**Issue by castaway** [Corion/WWW-Mechanize-Chrome#47]
https://github.com/Corion/WWW-Mechanize-Chrome/blob/3585e7725a12a3561eef91a0d857b861af02852b/lib/WWW/Mechanize/Chrome.pm#L4826

Says "the following query will work as expected:" .. and then stops..

**Comment by Corion** [comment]
This seems to be a rendering problem by Github, as the raw file contains the continuation of the sentence ( https://raw.githubusercontent.com/Corion/WWW-Mechanize-Chrome/3585e7725a12a3561eef91a0d857b861af02852b/lib/WWW/Mechanize/Chrome.pm ). On CPAN it also renders as expected, see https://metacpan.org/pod/WWW::Mechanize::Chrome . I don't even understand what could trigger the wrong rendering by Github here...

**Comment by Corion** [comment]
This was wrongly dismissed by me from GH #47 , but is actually correct. I've added to the documentation and pushed it as 40a2e0f24d268584871c432c366e8e4f804568ad .

Sorry and thanks!
