### ISSUE TITLE
Setting form fields does not seem to send pre and post events

### ISSUE THREAD

**Issue by davavra** [Corion/WWW-Mechanize-Chrome#53]
$mech->set_fields calls $mech->do_set_fields which in turn calls $mech->get_set_value.
$mech->get_set_value doesn't seem to send the pre and post events. In fact, there are only comments saying they will be sent. 

I need to send an "input" event for these and after the form is filled send an "ngSubmit" event to the form.

I could do this with WWW::Mechanize::Firefox but the ability to send events in the code seems to have vanished.

Was this intentional?

**Comment by Corion** [comment]
Hi,

thank you for using the module and reporting back on the problems you found!

On 05.04.20 05:57, davavra wrote:
> $mech->set_fields calls $mech->do_set_fields which in turn calls
> $mech->get_set_value.
> $mech->get_set_value doesn't seem to send the pre and post events. In
> fact, there are only comments saying they will be sent.
> 
> I need to send an "input" event for these and after the form is filled
> send an "ngSubmit" event to the form.
> 
> I could do this with WWW::Mechanize::Firefox but the ability to send
> events in the code seems to have vanished.
> 
> Was this intentional?

Whoops - no, this certainly was not intentional! It would be great if
you have a (single-file) HTML+JS file that I can use to reproduce the
problem with Angular. If not, that's not really problematic either, I
think I can set up some callbacks and check that they get called before
and after when setting an element value.

Thanks,
-max

**Comment by davavra** [comment]
It's a login page. I'd rather not reveal it or the content to the public. Can I PM it to you?

**Comment by Corion** [comment]
This is more for my lazyness with writing the tests myself and making sure my fix works for you. I've just pushed d53242f59e78aff187d8dbf3e90042cddba8a5ba , which could maybe be the fix you need already.

If this works for you, I'll add a test and release it onto CPAN.

If it doesn't work, you can reach me at `corion@corion.net` to send me the URL of the failing page so I can take a closer look.

**Comment by davavra** [comment]
It works. At least sent the post 'input" event to the field. I didn't really test the pre-events but the code likely works as it is the same as the pos-events.

**Comment by Corion** [comment]
Oh, that's a good spot! I'll fix that, thank you!

**Comment by davavra** [comment]
Looks great. I'll leave it to you to close the issue

**Comment by Corion** [comment]
Released as 0.47
