### ISSUE TITLE
Name of Chrome executable not accurate for Debian system

### ISSUE THREAD

**Issue by sdondley** [Corion/WWW-Mechanize-Chrome#8]
I installed Google Chrome on a Debian system using the procedure at https://www.tecmint.com/install-google-chrome-in-debian-ubuntu-linux-mint/

The name of the Google Chrome executable on my system as a result of following this procedure is `chrome-browser-stable` not `chrome-browser` as indicated in the documentation at:

https://metacpan.org/pod/WWW::Mechanize::Chrome#INSTALLING

Also, Debian allows you to install `google-chrome-beta` and `google-chrome-unstable`. 

I'd be happy to submit a patch to the docs to reflect the fact that the name of the executable may vary by OS flavor and that the user should consult their system specific documentation or system administrator for guidance.

Please let me know if you'd like me to submit a patch to make this improvement with any other suggestions for how this should be documented.

**Comment by Corion** [comment]
Yes, such a patch is very welcome! So far, I've only run the tests on an Ubuntu system, where the name is `chrome-browser` , but documenting the alternatives is very prudent!

Thank you very much for your analysis, feedback and for volunteering to provide a patch!

**Comment by sdondley** [comment]
I'm surprised Ubuntu would have a different executable name than Debian since Ubuntu uses the same packaging system. Perhaps it's because Ubuntu comes pre-installed with Chrome?
