### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by daw3gr** [Corion/WWW-Mechanize-Chrome#81]
Hello! Been trying for a day to install this module on a brand new ubuntu 22.04 with both Google Chrome/122.0.6261.128 and its chrome driver downloaded from   https://googlechromelabs.github.io/chrome-for-testing/#stable .

Have tried with cpan, cpanm and source, without and with chrome running (with --remote-debugging-port=9222) and with and without CHROME_BIN=/usr/bin/google-chrome-stable and installing from root or non root.

Chrome runs ok on display and can curl localhost:9222 if chrome is running with the flag above which gives an empty response.

The output of make test is always the same:
 Failed on Chrome version 'Google Chrome/122.0.6261.128': Could not read websocket endpoint from Chrome output. Do you maybe have a non-debug instance of Chrome already running? at /home/user1/WWW-Mechanize-Chrome-0.72/blib/lib/WWW/Mechanize/Chrome.pm line 1078.

**Comment by Corion** [comment]
The chrome driver is not required for WWW::Mechanize::Chrome to install.

Do you maybe have a non-debug instance of Chrome already running?

**Comment by daw3gr** [comment]
I've ended up being able to install it from source and as root. I think the problem may have arisen from installing from cpan or cpanm running the browser as root. No, there were no other instances of chrome running and now after installing Im able to run multiple windows concurrently by using different user directories. Many thanks for the module, will update if I find the root cause of the installation issue, pun intended :)

**Comment by Corion** [comment]
Oh - yes, I'm now looking at hardening the self-tests so they skip the problematic steps when running as root

**Comment by Corion** [comment]
This should be fixed with v0.73

**Comment by daw3gr** [comment]
Ace! :1st_place_medal:
