### ISSUE TITLE
Tests randomly hang

### ISSUE THREAD

**Issue by cmadamsgit** [Corion/WWW-Mechanize-Chrome#82]
I am building WWW::Mechanize::Chrome into an RPM package for Fedora Linux, including running make test (with Chromium under a virtual X server). However, I randomly hit a test hanging (not consistently the same test either). I set TEST_LOG_LEVEL=debug, and it seems that always when a test hangs, I get output like (this one from t/50-mech-text.t):

```
2024/06/12 09:52:05 Spawning for websocket $VAR1 = [
          '/usr/bin/chromium-browser',
          '--remote-debugging-port=0',
          '--remote-allow-origins=*',
          '--remote-debugging-address=127.0.0.1',
          '--user-data-dir=/tmp/Ke_NWL4sbq',
          '--no-first-run',
          '--mute-audio',
          '--no-default-browser-check',
          '--no-sandbox',
          '--safebrowsing-disable-auto-update',
          '--disable-background-networking',
          '--disable-background-timer-throttling',
          '--disable-backgrounding-occluded-windows',
          '--disable-breakpad',
          '--disable-default-apps',
          '--disable-dev-shm-usage',
          '--disable-domain-reliability',
          '--disable-gpu',
          '--disable-ipc-flooding-protection',
          '--disable-client-side-phishing-detection',
          '--disable-component-update',
          '--disable-hang-monitor',
          '--disable-popup-blocking',
          '--disable-prompt-on-repost',
          '--disable-renderer-backgrounding',
          '--disable-sync',
          '--disable-translate',
          '--disable-web-resources',
          '--headless',
          'about:blank'
        ];
2024/06/12 09:52:05 Spawned child as 2659, communicating via websocket
2024/06/12 09:52:05 Connecting to ws://127.0.0.1:34459/devtools/browser/53a829ea-35ff-4ec6-bbdf-662fdd0bac42
2024/06/12 09:52:05 Connected to ws://127.0.0.1:34459/devtools/browser/53a829ea-35ff-4ec6-bbdf-662fdd0bac42
2024/06/12 09:52:05 Attached to tab E83BA6676B2551CDE4B08ED7F77EE6F7, session 1F48B6696DEEBC097FA17B91E6233206
2024/06/12 09:52:05 Notifying listeners for 'Target.targetCreated'
2024/06/12 09:52:05 Ignoring 'Network.loadingFailed' (-:31A513F3A83272EB7AEF006870EFCEF9)
2024/06/12 09:52:05 Ignoring 'Page.frameStoppedLoading' (E83BA6676B2551CDE4B08ED7F77EE6F7:-)
2024/06/12 09:52:05 Ignoring 'Inspector.targetCrashed'
2024/06/12 09:52:05 Ignoring 'Target.targetCrashed'
```

Any ideas why that would happen, or how to avoid it?

This is testing on Fedora "rawhide" (development) branch, which has perl 5.38.2 and Chromium 125.0.6422.141.

**Comment by cmadamsgit** [comment]
This seems to happen more often on a faster system... maybe a race condition in there somewhere?

**Comment by Corion** [comment]
The `Target.targetCrashed` is new to me - I wonder what would be causing the Chrome / Chromium crash, since the tests only access local sources and don't vary between machines.

I also suspect a race condition or some race condition in Chrome, but so far I have been unable to isolate it.

**Comment by cmadamsgit** [comment]
I enabled the debug log and don't see anything odd... also, I'm not sure what crashed, as the chromium-browser processes are still running. I'll attach the debug log (it's from running in a mock chroot so can't connect to dbus or bluez, but those shouldn't be fatal).

Any other ideas to try to figure out what's happening? I'd like to get this accepted to Fedora, but skipping tests is not good (but tests hanging is definitely not good).
[chrome_debug.log](https://github.com/user-attachments/files/15921373/chrome_debug.log)

**Comment by cmadamsgit** [comment]
FYI this looks to be a bug in Chrome versions 125/126 where it sometimes crashes on startup due to an SELinux execheap denial (and then also sometimes gets an illegal instruction after that, but does not shut down, if not run headless it shows an error message with SIGILL). I see it with Chrome, Chromium, and now some Electron apps like Slack. Chrome devs broke something. :)

Since the tests in some ways are testing Chrome as much as the module itself (and that's not useful for packaging), I did go ahead and make running the tests optional (off by default), and have the package approved for Fedora that way. I'll just try to run the tests manually any time I update the Fedora package.
